"""user token public id

Revision ID: 5eb94ca0244a
Revises: 9989dab77c04
Create Date: 2018-06-26 10:36:05.054564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eb94ca0244a'
down_revision = '9989dab77c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user_token', sa.Column('user_public_id', sa.String(length=50), nullable=True))
    op.drop_constraint('api_user_token_ibfk_1', 'api_user_token', type_='foreignkey')
    op.drop_column('api_user_token', 'api_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user_token', sa.Column('api_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('api_user_token_ibfk_1', 'api_user_token', 'api_user', ['api_user_id'], ['id'])
    op.drop_column('api_user_token', 'user_public_id')
    # ### end Alembic commands ###
