"""One user store

Revision ID: 623ec1d43f19
Revises: e8518272c30d
Create Date: 2018-09-12 10:04:56.423894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '623ec1d43f19'
down_revision = 'e8518272c30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('public_id', table_name='websmap_user')
    op.drop_index('username', table_name='websmap_user')
    op.drop_table('websmap_user')
    op.drop_table('websmap_user_token')
    op.add_column('api_user', sa.Column('user_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_user', 'user_type')
    op.create_table('websmap_user_token',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('user_public_id', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('websmap_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('can_debit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('can_credit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'websmap_user', ['username'], unique=True)
    op.create_index('public_id', 'websmap_user', ['public_id'], unique=True)
    # ### end Alembic commands ###
