"""Recharges table

Revision ID: e8518272c30d
Revises: d2bbe1e701d6
Create Date: 2018-09-12 08:40:30.277392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8518272c30d'
down_revision = 'd2bbe1e701d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websmap_recharge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msisdn', sa.String(length=9), nullable=True),
    sa.Column('recharged', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('user_public_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websmap_recharge')
    # ### end Alembic commands ###
