"""api user virtual number

Revision ID: f892b3e50c75
Revises: f2c0c8be66fc
Create Date: 2018-09-03 15:39:30.055051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f892b3e50c75'
down_revision = 'f2c0c8be66fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user', sa.Column('virtual_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'api_user', ['virtual_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_user', type_='unique')
    op.drop_column('api_user', 'virtual_number')
    # ### end Alembic commands ###
